### PR TITLE
Adds needed wrappers for DAE problems

### PR DESCRIPTION
**Pull request by kanav99**
We would be needing to calculate jacobian of `f(tmp1 + γ1*z, tmp2 + γ2*z, p, t)` with respect to `z`. So we would be needing these wrappers for calculating this.

@ChrisRackauckas reviews

### CODE REVIEW

**Comment by kanav99** [comment]
> why the tmp2 part? Naive thought makes it f(tmp1 + γ1*z, z, p, t), but I'm not looking at the derivation right now. Maybe I'm forgetting someething

Actually I started with the same thinking. But I changed because we use nlsolve to calculate delta i.e we then add it to the `u`. So in most cases `tmp2` would be `uprev` and `γ2` would be one.

In any case, the wrapper would remain the same.

**Comment by ChrisRackauckas** [comment]
Explain more why it's needed.

**Comment by kanav99** [comment]
Use case of wrapper: The wrapper would be needed in the implementation of functions `dae_calc_J!` or `dae_update_W!`. They are WIP right now. Current `UJacobianWrapper` assumes 4 arguments which is not right for DAEs. Hence we need separate wrappers for them.

Use case of the form `f(tmp1 + γ1*z, z, p, t)`: As I mentioned, the exact reason I am using this form is to maintain consistency with original NLSolver. We use them to solve the differences, not the complete `u` (we do `u = uprev + nlsolver.z`). We can reuse the routines used for error esitmation directly then.

Even if we use the solver to directly calculate `u` , the wrapper would not change, or maybe slight changes. Let's not merge this right now, I will try to write all the derivative routines first and when the picture becomes further clear, then we should proceed.

**Comment by ChrisRackauckas** [comment]
This seems out of date now.

**Pull request closed without merging**
